name: worldwildprova
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2 #per les crides http
  shared_preferences: ^2.2.0 #per l'authentication
  flutter_secure_storage: ^9.0.0 #per l'authentication
  provider: ^6.1.0 #per l'authentication
  google_fonts: ^6.1.0 #canvi de lletres
  google_maps_flutter: ^2.1.1 #tot lo relacionat amb google maps
  geolocator: ^11.0.0 #tot lo relacionat amb google maps
  multi_select_flutter: ^4.1.3 #pels camps de multi-tria dels tags
  image_picker: ^1.0.4
  intl: ^0.20.2 #parsing de les dates
  google_sign_in: ^6.2.1 #sign up amb google
  smooth_page_indicator: ^1.0.0+2 #mostrar les onboarding cards
  jwt_decoder: ^2.0.1
  flutter_cache_manager: ^3.3.1
  image: ^4.1.3
  flutter_portal: ^1.1.1
  sticky_headers: ^0.3.0+2
  app_links: ^6.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/boton_buenosaires.png
    - assets/boton_sol.png
    - assets/map_pin.png

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: BebasNeueLight
      fonts:
        - asset: assets/fonts/BebasNeue-Light.ttf

    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/BarlowCondensed-SemiBold.ttf
      
    - family: BarlowCondensed_Regular
      fonts:
        - asset: assets/fonts/BarlowCondensed-Regular.ttf
