name: worldwildprova
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2 #per les crides http
  shared_preferences: ^2.2.0 #per l'authentication
  flutter_secure_storage: ^9.0.0 #per l'authentication
  provider: ^6.1.0 #per l'authentication
  google_fonts: ^6.1.0 #canvi de lletres
  google_maps_flutter: ^2.1.1 #tot lo relacionat amb google maps
  geolocator: ^11.0.0 #tot lo relacionat amb google maps
  multi_select_flutter: ^4.1.3 #pels camps de multi-tria dels tags
  image_picker: ^1.0.4
  intl: ^0.20.2 #parsing de les dates
  google_sign_in: ^6.2.1 #sign up amb google
  smooth_page_indicator: ^1.0.0+2 #mostrar les onboarding cards
  jwt_decoder: ^2.0.1
  flutter_cache_manager: ^3.3.1
  image: ^4.1.3
  flutter_portal: ^1.1.1
  sticky_headers: ^0.3.0+2
  app_links: ^6.4.0
  share_plus: ^8.0.0
  flutter_launcher_icons: ^0.12.0
  url_launcher: ^6.1.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpeg"


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/boton_buenosaires.png
    - assets/boton_sol.png
    - assets/map_pin.png
    - assets/ojitos.gif
    - assets/solocarita.png
    - assets/pincel3.png
    - assets/backgroundticketsimage.png
    - assets/explorar.png

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: BebasNeueLight
      fonts:
        - asset: assets/fonts/BebasNeue-Light.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-VariableFont_wght.ttf

    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Light.ttf
          weight: 400
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Regular.ttf
          weight: 500
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Medium.ttf
          weight: 600
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/BarlowCondensed/BarlowCondensed-Black.ttf
          weight: 900

        
       
